# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yohatana <yohatana@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/04 13:57:01 by yohatana          #+#    #+#              #
#    Updated: 2024/06/04 14:07:13 by yohatana         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= get_next_line.a

SRCS		= get_next_line.c get_next_line_utils.c

OBJS		=

CC			=
CCFLAGS		=

all:

clean:

fclean:

re:

.PHONY =
